In [2]:
import numpy as np
import pandas as pd

In [4]:
data = np.load('proyecto_training_data.npy')
print(data)

[[2.08500e+05 7.00000e+00 8.56000e+02 8.00000e+00 2.00300e+03 6.50000e+01]
 [1.81500e+05 6.00000e+00 1.26200e+03 6.00000e+00 1.97600e+03 8.00000e+01]
 [2.23500e+05 7.00000e+00 9.20000e+02 6.00000e+00 2.00100e+03 6.80000e+01]
 ...
 [2.66500e+05 7.00000e+00 1.18800e+03 9.00000e+00 1.94100e+03 6.60000e+01]
 [1.42125e+05 5.00000e+00 1.07800e+03 5.00000e+00 1.95000e+03 6.80000e+01]
 [1.47500e+05 5.00000e+00 1.25600e+03 6.00000e+00 1.96500e+03 7.50000e+01]]


In [6]:
dataset = pd.DataFrame(data, columns=['SalePrice', 'OverallQual', '1stFlrSF', 'TotRmsAbvGrd', 'YearBuilt', 'LotFrontage'])
dataset.head()

SalePrice  OverallQual  1stFlrSF  TotRmsAbvGrd  YearBuilt  LotFrontage
0   208500.0          7.0     856.0           8.0     2003.0         65.0
1   181500.0          6.0    1262.0           6.0     1976.0         80.0
2   223500.0          7.0     920.0           6.0     2001.0         68.0
3   140000.0          7.0     961.0           7.0     1915.0         60.0
4   250000.0          8.0    1145.0           9.0     2000.0         84.0

In [9]:
# Obtener tipos del dataset
dataset.dtypes

SalePrice       float64
OverallQual     float64
1stFlrSF        float64
TotRmsAbvGrd    float64
YearBuilt       float64
LotFrontage     float64
dtype: object

In [7]:
# Analisis rapido del dataset
dataset.describe() 

SalePrice  OverallQual     1stFlrSF  TotRmsAbvGrd    YearBuilt  \
count    1460.000000  1460.000000  1460.000000   1460.000000  1460.000000   
mean   180921.195890     6.099315  1162.626712      6.517808  1971.267808   
std     79442.502883     1.382997   386.587738      1.625393    30.202904   
min     34900.000000     1.000000   334.000000      2.000000  1872.000000   
25%    129975.000000     5.000000   882.000000      5.000000  1954.000000   
50%    163000.000000     6.000000  1087.000000      6.000000  1973.000000   
75%    214000.000000     7.000000  1391.250000      7.000000  2000.000000   
max    755000.000000    10.000000  4692.000000     14.000000  2010.000000   

       LotFrontage  
count  1201.000000  
mean     70.049958  
std      24.284752  
min      21.000000  
25%      59.000000  
50%      69.000000  
75%      80.000000  
max     313.000000

In [10]:
# Ver el porcentaje de datos nulos por cada columna
columnas = dataset.columns
for col in columnas:
    porcentaje_na = dataset[col].isnull().mean()
    print(f"{col}: {porcentaje_na}")

SalePrice: 0.0
OverallQual: 0.0
1stFlrSF: 0.0
TotRmsAbvGrd: 0.0
YearBuilt: 0.0
LotFrontage: 0.1773972602739726


In [11]:
# Reemplazar los datos nulos 
# Para corregir esto, podemos imputar la media (sustituir los valores NaN por la media)
promedio = dataset['LotFrontage'].mean()
dataset['LotFrontage'].fillna(promedio, inplace=True)

In [12]:
# Verificamos de nuevo el porcentaje de datos nulos
columnas = dataset.columns
for col in columnas:
    porcentaje_na = dataset[col].isnull().mean()
    print(f"{col}: {porcentaje_na}")

SalePrice: 0.0
OverallQual: 0.0
1stFlrSF: 0.0
TotRmsAbvGrd: 0.0
YearBuilt: 0.0
LotFrontage: 0.0
